/**
 * Product data for product detail pages.
 * Keys are URL slugs (e.g. cloudfish, tidesync).
 */
export const PRODUCT_PAGES = {
  cloudfish: {
    name: 'CloudFish',
    tagline: 'Streamline operations with intelligent cloud workflows.',
    logo: '/cloudfish/cloudfish-logo.png',
    description:
      'CloudFish is our prompt-powered, agentic query tool designed to eliminate the complexity of Oracle Cloud databases. Built with 30 years of Oracle DNA, CloudFish empowers your team to bypass complex SQL and manual data modeling through a natural language interface that talks directly to your HCM and ERP records. Whether you are analyzing workforce trends or financial metrics, our AI-driven digital coworkers execute end-to-end data tasks—delivering clear, actionable insights and instant exports with fewer clicks.',
    gradient: 'from-aqua to-aqua-light',
    heroSlides: [
      { title: 'Stop Writing SQL. Start Querying with REST API. Only on CloudFish', image: '/cloudfish/oracle-fusion-hcm-rest-apis.png', textTone: 'light' },
      { title: 'Oracle Cloud Workforce Reports and Analytics in one single place.', image: '/cloudfish/oracle-hcm-workforce.png', textTone: 'light' },
      { title: 'No Multi layer Technical Maze – No Table Hunting.', image: '/cloudfish/bi-publisher-easy-reporting-combined.png', textTone: 'dark' },
      { title: 'REST, SQL & JSON with CloudFish', image: '/cloudfish/cloudfish-rest-sql-json-ords.png', textTone: 'light' },
      { title: '', image: '/cloudfish/cloudfish-all-in-one-platform-funky.png', textTone: 'dark' },
    ],
    ctaLoginHref: 'https://cloudfish.slpmicrosystems.com/login',
    ctaTrialHref: '/#contact',
    ctaOpenAppHref: 'https://cloudfish.slpmicrosystems.com/',
    ctaOpenAppLabel: 'Open CloudFish',
    appPreview: {
      title: 'CloudFish For You',
      subtitle: 'Connections, DB Browser, worksheets, and query results—all in one place.',
      image: '/cloudfish/cloudfish-for-you-bg.png',
      ctaLabel: 'Open CloudFish',
      ctaHref: 'https://cloudfish.slpmicrosystems.com/',
    },
    features: {
      title: 'Features',
      subtitle: 'Everything you need to query Oracle Cloud without the hassle.',
      items: [
        { icon: '⚡', title: 'HCM REST Resource & SQL (ORDS / custom endpoint)', badge: 'Only in CloudFish', description: 'Run HCM REST resources and SQL together—including ORDS and custom endpoints—in one tool. No other tool offers this.', highlight: true },
        { icon: '🔐', title: 'Single Sign-On (SSO)', badge: 'Enterprise', description: 'Enterprise customers can use Single Sign-On—one login for your identity provider and CloudFish. Secure, seamless access for your team. Simply create an SSO connection in CloudFish, and when you connect, your organization\'s login window will handle authentication.', highlight: true },
        { icon: '☁️', title: 'Web-based, No Need To Download and install', description: 'Access from anywhere. No client extensions or downloads.' },
        { icon: '🔌', title: 'SQL in Oracle Cloud', description: 'Run SQL against Oracle Cloud data—HCM, ERP, SCM, PPM—with one tool.' },
        { icon: '🌐', title: 'Multiple connections', description: 'Connect to several cloud instances at once and switch between them easily. Create Multiple Connections and rename them as you wish.' },
        { icon: '📊', title: 'Export to Excel & CSV, DAT AND PDF formats', description: 'Export results to .xls and .csv for reports and analysis.' },
        { icon: '🔍', title: 'DB Browser – packages & code', description: 'See all packages in the database and open any package to view its code. Browse Fusion tables and build queries with full visibility.' },
        { icon: '📋', title: 'Search tables & columns, click to copy', description: 'Search all available tables with column names. Click a table name and it copies straight into the query editor.' },
        { icon: '🤖', title: 'AI Assistant to build query in natural language', description: 'Describe what you need in plain English and get SQL generated for Oracle Cloud tables—no syntax memorization required.', highlight: true },
        { icon: '✨', title: 'Intellisense & Formatting', description: 'Smart editor with auto-completion, SQL formatting, and code snippets.' },
        { icon: '📜', title: 'SQL History', description: 'CloudFish keeps all your queries for ready reference. Every query you run is automatically saved in your history, so you can always go back and find it.' },
        { icon: '💬', title: 'Clear Oracle error messages', description: 'Get clear, readable Oracle error messages so you can fix issues faster and code with less guesswork.' },
      ],
    },
    pricing: {
      title: 'Choose Plan',
      subtitle: 'Choose the right plan that fits your team.',
      loginHref: '/login',
      plans: [
        {
          name: 'Free Trial',
          variant: 'silver',
          planId: 'free_trial',
          price: '$0',
          period: '',
          note: 'Full access for 7 days',
          description: '1 connection, 1 worksheet. Try CloudFish risk-free.',
          features: ['Intellisense & SQL formatting', 'Clear Oracle error messages', 'Export to Excel/CSV/PDF', 'SQL History'],
          ctaLabel: 'Start free trial',
        },
        {
          name: 'Silver',
          variant: 'silver',
          planId: 'silver',
          price: '$30',
          period: '/month',
          note: 'Valid for 1 month',
          description: '2 worksheets, 2 ERP/HCM/PPM Cloud connections',
          features: [
            'Intellisense & SQL formatting',
            'Clear Oracle error messages',
            '2 worksheets, 2 connections',
            'SQL History to reuse past queries',
          ],
        },
        {
          name: 'Gold',
          variant: 'gold',
          planId: 'gold',
          price: '$40',
          period: '/month',
          note: 'Valid for 1 month',
          description: 'Unlimited connections, unlimited worksheets',
          features: [
            'Unlimited worksheets and connections',
            'AI Assistant for query generation',
            'Export to Excel/CSV/DAT/PDF',
            'Email support',
          ],
        },
        {
          name: 'Gold-Yearly',
          variant: 'gold-yearly',
          planId: 'gold_yearly',
          price: '$450',
          period: '/year',
          note: 'Valid for 12 months',
          description: 'Unlimited ERP/HCM/PPM Cloud connections',
          features: [
            'Everything in Gold',
            'REST API query without SQL',
            'ORDS and custom endpoint support',
            'Tables and packages browser',
          ],
        },
        {
          name: 'Enterprise Plan',
          variant: 'enterprise',
          planId: 'enterprise',
          price: 'Call us',
          period: '/year',
          note: 'Best value for organizations',
          description: 'Unlimited Cloud connections and users',
          featured: true,
          features: [
            'Unlimited PODs and users',
            'Single Sign-On (SSO)',
            '24/7 support',
            'Regular updates & useful query packs',
          ],
        },
      ],
    },
  },
  tidesync: {
    name: 'TideSync',
    tagline: 'Unified data and workflows across your Oracle Cloud ecosystem.',
    logo: '/tidesync-product-logo.png',
    description:
      'TideSync unifies data and workflows across your Oracle Cloud ecosystem. Keep HCM, ERP, and analytics in sync with automated pipelines, consistent security, and a single pane of glass. Reduce integration overhead and get a unified view of your Oracle landscape so your team can focus on decisions, not data wrangling.',
    gradient: 'from-teal to-teal-sea',
    heroSlides: [
      {
        image: '/tidesync/hero-slide-1-your-rules.png',
        imageFit: 'cover',
        imagePosition: 'object-top',
        textTone: 'light',
        ctaLabel: 'Request a custom build',
        ctaHref: 'mailto:info@slpmicrosystems.com?subject=TideSync%20Custom%20Build%20Request',
        ctaStyle: 'yellow',
      },
      {
        image: '/tidesync/hero-slide-2-bridge-integration.png',
        imageFit: 'cover',
        imagePosition: 'object-center',
        textTone: 'light',
        ctaLabel: 'Explore the integration',
        ctaHref: '/products/tidesync#integration',
        ctaStyle: 'yellow',
      },
      {
        image: '/tidesync/hero-slide-3-error-management.png',
        imageFit: 'cover',
        imagePosition: 'object-center',
        textTone: 'light',
        ctaLabel: 'Start today',
        ctaHref: '/products/tidesync#contact-tidesync',
        ctaStyle: 'yellow',
      },
      {
        image: '/tidesync/hero-slide-4-secure-archiving.png',
        imageFit: 'cover',
        imagePosition: 'object-center',
        textTone: 'light',
        ctaLabel: 'Learn about data retention',
        ctaHref: '/products/tidesync#data-retention',
        ctaStyle: 'yellow',
      },
    ],
    ctaLoginHref: '/login',
    ctaContactHref: '#contact-tidesync',
    ctaOpenAppHref: 'https://tidesync.slpmicrosystems.com/',
    ctaOpenAppLabel: 'Open TideSync',
    features: {
      title: 'Features',
      subtitle: 'One platform. Unified data. Less complexity.',
      items: [
        { icon: '🔄', title: 'Automated Pipelines', description: 'Keep HCM, ERP, and analytics in sync with automated data pipelines.' },
        { icon: '🔒', title: 'Consistent Security', description: 'Enterprise-grade security across all your Oracle Cloud systems.' },
        { icon: '📊', title: 'Single Pane of Glass', description: 'A unified view of your Oracle landscape—no more switching between tools.' },
        { icon: '⚡', title: 'Reduce Integration Overhead', description: 'Focus on decisions, not data wrangling.' },
        { icon: '🌐', title: 'Oracle Cloud Native', description: 'Built for Oracle Cloud HCM, ERP, SCM, and PPM.' },
        { icon: '🤝', title: 'Managed Sync', description: 'Reliable, repeatable workflows for your critical business data.' },
      ],
    },
    contactSection: {
      title: 'Get in Touch',
      subtitle: 'Interested in TideSync? Contact us for pricing and a demo.',
      buttonLabel: 'Contact us',
    },
    pricing: {
      title: 'Choose Plan',
      subtitle: 'Pick the TideSync tier that matches your time collection and Oracle OTL needs.',
      loginHref: '/login',
      plans: [
        {
          name: 'Gold',
          variant: 'gold',
          planId: 'tidesync_gold',
          price: '$5,000',
          period: '/ 6 months',
          note: 'Billed every 6 months',
          description: 'Full TideSync for time collection, sync, and approved hours in Oracle Time & Labor.',
          features: [
            'Email support',
            'Export to CSV, Excel, and more',
            'Multiple time collection devices',
            'Approved hours by employee',
            'Approved hours by date range',
          ],
          ctaLabel: 'Buy now',
        },
        {
          name: 'Enterprise',
          variant: 'enterprise',
          planId: 'enterprise',
          price: 'Contact us',
          period: '',
          note: 'Custom pricing for your organization',
          description: 'Volume licensing, advanced requirements, and tailored rollout.',
          features: [
            'Email support',
            'Export to CSV, Excel, and more',
            'Multiple time collection devices',
            'Approved hours by employee',
            'Approved hours by date range',
          ],
          ctaLabel: 'Contact Us',
        },
      ],
    },
  },
};

export function getProductBySlug(slug) {
  return PRODUCT_PAGES[slug] ?? null;
}

export function getAllProductSlugs() {
  return Object.keys(PRODUCT_PAGES);
}
